[package]
name = "rust-roguelike"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
rltk = "0.8.7"
web-sys = { version = "0.3.77", features = ["Window", "Document", "HtmlElement", "Text"] }
